records/urls.py
from django.urls import path
from .import views

app_name = 'records'
urlpatterns = [
    path('', views.home, name='home'),
    path('add_details/', views.add_details, name='add_details'),
    path('mech_details/', views.mech_details, name='mech_details'),
    path('elect_details/', views.elect_details, name='elect_details'),
    path('civil_details/', views.civil_details, name='civil_details'),
    path('comp_engr_details/', views.comp_engr_details, name='comp_engr_details'),
    path('agric_engr_details/', views.agric_engr_details, name='agric_engr_details'),
    path('computer_science_details/', views.computer_science_details, name='computer_science_details'),
    path('science_lab_details/', views.science_lab_details, name='science_lab_details'),
    path('food_tech_details/', views.food_tech_details, name='food_tech_details'),
    path('pharm_tech_details/', views.pharm_tech_details, name='pharm_tech_details'),
    path('dispense_details/', views.dispense_details, name='dispense_details'),
    path('delete_mech/<int:mech_id>/', views.delete_mech, name='delete_mech'),
    path('delete_elect/<int:elect_id>/', views.delete_elect, name='delete_elect'),
    path('delete_civil/<int:civil_id>/', views.delete_civil, name='delete_civil'),
    path('delete_comp_engr/<int:comp_engr_id>/', views.delete_comp_engr, name='delete_comp_engr'),
    path('delete_comp_sci/<int:comp_sci_id>/', views.delete_comp_sci, name='delete_comp_sci'),
    path('delete_agric/<int:agric_id>/', views.delete_agric, name='delete_agric'),
    path('delete_sci_lab/<int:sci_lab_id>/', views.delete_sci_lab, name='delete_sci_lab'),
    path('delete_food/<int:food_id>/', views.delete_food, name='delete_food'),
    path('delete_pharm/<int:pharm_id>/', views.delete_pharm, name='delete_pharm'),
    path('delete_dispense/<int:dispense_id>/', views.delete_dispense, name='delete_dispense'),
    path('mech_update/<int:id>/', views.mech_update, name='mech_update'),
    path('elect_update/<int:id>/', views.elect_update, name='elect_update'),
    path('civil_update/<int:id>/', views.civil_update, name='civil_update'),
    path('comp_sci_update/<int:id>/', views.comp_sci_update, name='comp_sci_update'),
    path('comp_engr_update/<int:id>/', views.comp_engr_update, name='comp_engr_update'),
    path('pharm_update/<int:id>/', views.pharm_update, name='pharm_update'),
    path('sci_lab_update/<int:id>/', views.sci_lab_update, name='sci_lab_update'),
    path('food_update/<int:id>/', views.food_update, name='food_update'),
    path('dispense_update/<int:id>/', views.dispense_update, name='dispense_update'),
    path('agric_update/<int:id>/', views.agric_update, name='agric_update'),
    path('search/', views.search, name='search'),
]

tutorials/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('records.urls')),
    path('admin/', admin.site.urls),
]

records/forms.py
from django import forms

DEPT_CHOICES = (
    ('ME', 'Mechanical Engineering'),
    ('EE', 'Electrical Engineering'),
    ('CE', 'Civil Engineering'),
    ('CTE', 'Computer Engineering'),
    ('AE', 'Agricultural Engineering'),
    ('CS', 'Computer Science'),
    ('SLT', 'Science Laboratory Technology'),
    ('FST', 'Food Science Technology'),
    ('PT', 'Pharmaceutical Technology'),
    ('DOP', 'Dispensary and Opticiary')
)
class DeptForm(forms.Form):
    dept = forms.CharField(
        max_length=20,
        widget=forms.Select(choices=DEPT_CHOICES)
    )
    name = forms.CharField(label='Your name', max_length=200)
    amount = forms.DecimalField(label='amount', max_digits=10, decimal_places=2)
    balance = forms.DecimalField(label='balance', max_digits=10, decimal_places=2)
    total = forms.DecimalField(label='total', max_digits=10, decimal_places=2)

records/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .forms import DeptForm
from django.db.models import Q
from django.db.models import Sum
from .models import (
    Mechanical_Dept,
    Electrical_Dept,
    Civil_Dept,
    Computer_Science_Dept,
    Comp_Engr_Dept,
    Pharmaceutical_Tech_Dept,
    Science_Lab_Tech_Dept,
    Food_Tech_Dept,
    Dispensary_and_Opticiary_Dept,
    Agric_Engr_Dept
)
from django.http import HttpResponseRedirect

# Create your views here.

def home(request):
    form = DeptForm()
    return render(request, 'records/index.html', {
        'form': form
    })
    
def mech_details(request):
    mech_lists = Mechanical_Dept.objects.all().order_by('id')
    mech_total = Mechanical_Dept.objects.aggregate(Sum('total'))
    total = mech_total['total__sum']
    
    if mech_lists:
        return render(request, 'records/mech_engr.html', {
            'mech_lists': mech_lists,
            'total': total
        })
    else:
        department = 'Mechanical Engineering'
        none = 'No records found..'
        return render(request, 'records/none.html', {
            'department': department,
            'none': none
        })    

def elect_details(request):
    elect_lists = Electrical_Dept.objects.all().order_by('id')
    elect_total = Electrical_Dept.objects.aggregate(Sum('total'))
    total = elect_total['total__sum']
    if elect_lists:
        return render(request, 'records/elect_engr.html', {
            'elect_lists': elect_lists,
            'total': total
        })
    else:
        department = 'Electrical Engineering'
        none = 'No records found..'
        return render(request, 'records/none.html', {
            'department': department,
            'none': none
        }) 

def civil_details(request):
    civil_lists = Civil_Dept.objects.all().order_by('id')
    civil_total = Civil_Dept.objects.aggregate(Sum('total'))
    total = civil_total['total__sum']
    if civil_lists:
        return render(request, 'records/civil_engr.html', {
            'civil_lists': civil_lists,
            'total': total
        })
    else:
        department = 'Civil Engineering'
        none = 'No records found..'
        return render(request, 'records/none.html', {
            'department': department,
            'none': none
        })  

def comp_engr_details(request):
    comp_engr_lists = Comp_Engr_Dept.objects.all().order_by('id')
    comp_engr_total = Comp_Engr_Dept.objects.aggregate(Sum('total'))
    total = comp_engr_total['total__sum']
    if comp_engr_lists:
        return render(request, 'records/comp_engr.html', {
            'comp_engr_lists': comp_engr_lists,
            'total': total
        })
    else:
        department = 'Computer Engineering'
        none = 'No records found..'
        return render(request, 'records/none.html', {
            'department': department,
            'none': none
        })  

def agric_engr_details(request):
    agric_engr_lists = Agric_Engr_Dept.objects.all().order_by('id')
    agric_engr_total = Agric_Engr_Dept.objects.aggregate(Sum('total'))
    total = agric_engr_total['total__sum']
    if agric_engr_lists:
        return render(request, 'records/agric_engr.html', {
            'agric_engr_lists': agric_engr_lists,
            'total': total
        })
    else:
        department = 'Agricultural Engineering'
        none = 'No records found..'
        return render(request, 'records/none.html', {
            'department': department,
            'none': none
        })  

def computer_science_details(request):
    science_lists = Computer_Science_Dept.objects.all().order_by('id')
    science_total = Computer_Science_Dept.objects.aggregate(Sum('total'))
    total = science_total['total__sum']
    if science_lists:
        return render(request, 'records/comp_sci.html', {
            'science_lists': science_lists,
            'total': total
        })
    else:
        department = 'Computer Science'
        none = 'No records found..'
        return render(request, 'records/none.html', {
            'department': department,
            'none': none
        })  

def science_lab_details(request):
    science_lab_lists = Science_Lab_Tech_Dept.objects.all().order_by('id')
    sci_lab_total = Science_Lab_Tech_Dept.objects.aggregate(Sum('total'))
    total = sci_lab_total['total__sum']
    if science_lab_lists:
        return render(request, 'records/sci_lab_tech.html', {
            'science_lab_lists': science_lab_lists,
            'total': total
        })
    else:
        department = 'Science Laboratory Technology'
        none = 'No records found..'
        return render(request, 'records/none.html', {
            'department': department,
            'none': none
        })  

def food_tech_details(request):
    food_lists = Food_Tech_Dept.objects.all().order_by('id')
    food_total = Food_Tech_Dept.objects.aggregate(Sum('total'))
    total = food_total['total__sum']
    if food_lists:
        return render(request, 'records/food_tech.html', {
            'food_lists': food_lists,
            'total': total
        })
    else:
        department = 'Food Science Technology'
        none = 'No records found..'
        return render(request, 'records/none.html', {
            'department': department,
            'none': none
        }) 

def pharm_tech_details(request):
    pharm_lists = Pharmaceutical_Tech_Dept.objects.all().order_by('id')
    pharm_total = Pharmaceutical_Tech_Dept.objects.aggregate(Sum('total'))
    total = pharm_total['total__sum']
    if pharm_lists:
        return render(request, 'records/pharm_tech.html', {
            'pharm_lists': pharm_lists,
            'total':total
        })
    else:
        department = 'Pharmaceutical Technology'
        none = 'No records found..'
        return render(request, 'records/none.html', {
            'department': department,
            'none': none
        }) 

def dispense_details(request):
    dispensary_lists = Dispensary_and_Opticiary_Dept.objects.all().order_by('id')
    dispense_total = Dispensary_and_Opticiary_Dept.objects.aggregate(Sum('total'))
    total = dispense_total['total__sum']
    if dispensary_lists:
        return render(request, 'records/opticiary.html', {
            'dispensary_lists': dispensary_lists,
            'total': total
        })
    else:
        department = 'Dispensary and Opticiary'
        none = 'No records found..'
        return render(request, 'records/none.html', {
            'department': department,
            'none': none
        })  


def add_details(request):
    current_date = timezone.now()
    if request.method == 'POST':
        form = DeptForm(request.POST)
        if form.is_valid():
            dept = form.cleaned_data['dept']
            name = form.cleaned_data['name']
            amount = form.cleaned_data['amount']
            balance = form.cleaned_data['balance']
            total = form.cleaned_data['total']
            if dept == 'ME':
                Mechanical_Dept.objects.create(added_date=current_date, name_of_students=name, amount=amount, balance=balance, total=total)
                return HttpResponseRedirect('/mech_details')
            if dept =='EE':
                Electrical_Dept.objects.create(added_date=current_date, name_of_students=name, amount=amount, balance=balance, total=total)
                return HttpResponseRedirect('/elect_details')
            if dept =='CE':
                Civil_Dept.objects.create(added_date=current_date, name_of_students=name, amount=amount, balance=balance, total=total)
                return HttpResponseRedirect('/civil_details')
            if dept =='CTE':
                Comp_Engr_Dept.objects.create(added_date=current_date, name_of_students=name, amount=amount, balance=balance, total=total)
                return HttpResponseRedirect('/comp_engr_details')
            if dept =='AE':
                Agric_Engr_Dept.objects.create(added_date=current_date, name_of_students=name, amount=amount, balance=balance, total=total)
                return HttpResponseRedirect('/agric_engr_details')
            if dept =='CS':
                Computer_Science_Dept.objects.create(added_date=current_date, name_of_students=name, amount=amount, balance=balance, total=total)
                return HttpResponseRedirect('/computer_science_details')
            if dept =='SLT':
                Science_Lab_Tech_Dept.objects.create(added_date=current_date, name_of_students=name, amount=amount, balance=balance, total=total)
                return HttpResponseRedirect('/science_lab_details')
            if dept =='FST':
                Food_Tech_Dept.objects.create(added_date=current_date, name_of_students=name, amount=amount, balance=balance, total=total)
                return HttpResponseRedirect('/food_tech_details')
            if dept =='PT':
                Pharmaceutical_Tech_Dept.objects.create(added_date=current_date, name_of_students=name, amount=amount, balance=balance, total=total)
                return HttpResponseRedirect('/pharm_tech_details')
            if dept =='DOP':
                Dispensary_and_Opticiary_Dept.objects.create(added_date=current_date, name_of_students=name, amount=amount, balance=balance, total=total)
                return HttpResponseRedirect('/dispense_details')

    else:
        form = DeptForm()
        return render(request, 'records/index.html', {
            'form': form
        })

def delete_mech(request, mech_id):
    Mechanical_Dept.objects.get(id=mech_id).delete()
    return HttpResponseRedirect("/mech_details")

def delete_elect(request, elect_id):
    Electrical_Dept.objects.get(id=elect_id).delete()
    return HttpResponseRedirect("/elect_details")

def delete_civil(request, civil_id):
    Civil_Dept.objects.get(id=civil_id).delete()
    return HttpResponseRedirect("/civil_details")

def delete_comp_engr(request, comp_engr_id):

templates/records/agric_engr.html
{% extends 'base.html' %}

{% block title %}Agricultural Engineering Account{% endblock %}
{% block content %}
    <div class="row mt-4">
        <div class="col">
            <ul class="list-group">
                    <h5> Agricultural Engineering Account Details for First Semester Tutorials</h5>
                    <h5>Total Amount for Agricultural Engineering: {{ total }}</h5>
                    <div class="row mt-4">
                        <div class="col-8">
                            <table class="table">
                                <thead class="thead">
                                    <tr>
                                    <th scope="col">S/NO</th>
                                    <th scope="col">NAME OF STUDENTS</th>
                                    <th scope="col">AMOUNT</th>
                                    <th scope="col">BALANCE</th>
                                    <th scope="col">TOTAL</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                    {% for agric_engr_list in agric_engr_lists %}
                    <div class="row">
                        <div class="col-12">
                            <table class="table">
                                <tbody>
                                    <tr class="data">
                                        <th scope="row">{{ agric_engr_list.id }}</th>
                                        <td>{{ agric_engr_list.name_of_students }}</td>
                                        <td>{{ agric_engr_list.amount }}</td>
                                        <td>{{ agric_engr_list.balance }}</td>
                                        <td>{{ agric_engr_list.total }}</td>

                                        <td><a id="update" href="{% url 'records:agric_update' agric_engr_list.id %}">Update</a></td>
                                        <td>
                                            <div class="float-right">
                                            <form action="{% url 'records:delete_agric' agric_engr_list.id %}" method="post">
                                                {% csrf_token %}
                                                <button type="submit" id="delete">Delete</button>
                                            </form>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>         
                        </div>
                    </div>
                        
                    {% endfor %}
             
                
            </ul>
        </div>
    </div>
{% endblock content %}

templates/records/civil_engr.html
{% extends 'base.html' %}

{% block title %}Civil Engineering Account{% endblock %}
{% block content %}
    <div class="row mt-4">
        <div class="col">
            <ul class="list-group">
                    <h5> Civil Engineering Account Details for First Semester Tutorials</h5>
                    <h5>Total Amount for Civil Engineering: {{ total }}</h5>
                    <div class="row mt-4">
                        <div class="col-8">
                            <table class="table">
                                <thead class="thead">
                                    <tr>
                                    <th scope="col">S/NO</th>
                                    <th scope="col">NAME OF STUDENTS</th>
                                    <th scope="col">AMOUNT</th>
                                    <th scope="col">BALANCE</th>
                                    <th scope="col">TOTAL</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                    {% for civil_list in civil_lists %}
                    <div class="row">
                        <div class="col-12">
                            <table class="table">
                                <tbody>
                                    <tr class="data">
                                        <th scope="row">{{ civil_list.id }}</th>
                                        <td>{{ civil_list.name_of_students }}</td>
                                        <td>{{ civil_list.amount }}</td>
                                        <td>{{ civil_list.balance }}</td>
                                        <td>{{ civil_list.total }}</td>

                                        <td><a id="update" href="{% url 'records:civil_update' civil_list.id %}">Update</a></td>
                                        <td>
                                            <div class="float-right">
                                            <form action="{% url 'records:delete_civil' civil_list.id %}" method="post">
                                                {% csrf_token %}
                                                <button type="submit" id="delete">Delete</button>
                                            </form>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>         
                        </div>
                    </div>
                        
                    {% endfor %}
             
                
            </ul>
        </div>
    </div>
{% endblock content %}

templates/records/comp_engr.html
{% extends 'base.html' %}

{% block title %}Computer Engineering Account{% endblock %}
{% block content %}
    <div class="row mt-4">
        <div class="col">
            <ul class="list-group">
                    <h5> Computer Engineering Account Details for First Semester Tutorials</h5>
                    <h5>Total Amount for Computer Engineering: {{ total }}</h5>
                    <div class="row mt-4">
                        <div class="col-8">
                            <table class="table">
                                <thead class="thead">
                                    <tr>
                                    <th scope="col">S/NO</th>
                                    <th scope="col">NAME OF STUDENTS</th>
                                    <th scope="col">AMOUNT</th>
                                    <th scope="col">BALANCE</th>
                                    <th scope="col">TOTAL</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                    {% for comp_engr_list in comp_engr_lists %}
                    <div class="row">
                        <div class="col-12">
                            <table class="table">
                                <tbody>
                                    <tr class="data">
                                        <th scope="row">{{ comp_engr_list.id }}</th>
                                        <td>{{ comp_engr_list.name_of_students }}</td>
                                        <td>{{ comp_engr_list.amount }}</td>
                                        <td>{{ comp_engr_list.balance }}</td>
                                        <td>{{ comp_engr_list.total }}</td>

                                        <td><a id="update" href="{% url 'records:comp_engr_update' comp_engr_list.id %}">Update</a></td>
                                        <td>
                                            <div class="float-right">
                                            <form action="{% url 'records:delete_comp_engr' comp_engr_list.id %}" method="post">
                                                {% csrf_token %}
                                                <button type="submit" id="delete">Delete</button>
                                            </form>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>         
                        </div>
                    </div>
                        
                    {% endfor %}
             
                
            </ul>
        </div>
    </div>
{% endblock content %}

templates/records/comp_sci.html
{% extends 'base.html' %}

{% block title %}Computer Science Account{% endblock %}
{% block content %}
    <div class="row mt-4">
        <div class="col">
            <ul class="list-group">
                    <h5> Computer Science Account Details for First Semester Tutorials</h5>
                    <h5>Total Amount for Computer Science: {{ total }}</h5>
                    <div class="row mt-4">
                        <div class="col-8">
                            <table class="table">
                                <thead class="thead">
                                    <tr>
                                    <th scope="col">S/NO</th>
                                    <th scope="col">NAME OF STUDENTS</th>
                                    <th scope="col">AMOUNT</th>
                                    <th scope="col">BALANCE</th>
                                    <th scope="col">TOTAL</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                    {% for science_list in science_lists %}
                    <div class="row">
                        <div class="col-12">
                            <table class="table">
                                <tbody>
                                    <tr class="data">
                                        <th scope="row">{{ science_list.id }}</th>
                                        <td>{{ science_list.name_of_students }}</td>
                                        <td>{{ science_list.amount }}</td>
                                        <td>{{ science_list.balance }}</td>
                                        <td>{{ science_list.total }}</td>

                                        <td><a id="update" href="{% url 'records:comp_sci_update' science_list.id %}">Update</a></td>
                                        <td>
                                            <div class="float-right">
                                            <form action="{% url 'records:delete_comp_sci' science_list.id %}" method="post">
                                                {% csrf_token %}
                                                <button type="submit" id="delete">Delete</button>
                                            </form>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>         
                        </div>
                    </div>
                        
                    {% endfor %}
             
                
            </ul>
        </div>
    </div>
{% endblock content %}

templates/records/index.html
{% extends 'base.html' %}

{% block content %}

<div class="row mt-4">
    <div class="col-12">
        <h4 class=""> Departmental Account Details for First Semester Tutorials</h4>
        <h6>PLEASE FILL OUT THE FORM</h6>
        <div class="row">
            <form action="{% url 'records:add_details' %}" method="post" class="form-group">
                {% csrf_token %}
                
                    {{ form.as_p  }}
                
                <button type="submit" class="btn btn-primary mb-2">Submit</button>
                
                
                
            </form>
        </div>
        
    </div>
</div>

{% endblock content %}

templates/records/search.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col mt-4">
        {% if submitbutton == 'Search' and request.GET.search != '' %}
            {% if results %}
                <h4>Results for <b>{{ request.GET.search }} in mechanical engineering</b></h4>
                {% for result in results %}
                   <a href="{% url 'records:mech_details' %}"><h5>Name: {{ result.name_of_students }}</h5></a>
                   <h5>ID: {{ result.id }}</h5>
                    <h5>Amount: {{ result.amount }}</h5>
                    <h5>Balance: {{ result.balance }}</h5>
                {% endfor %}
            {% endif %}
            {% if elect_results %}
                <h4>Results for <b>{{ request.GET.search }} in electrical engineering</b></h4>
                {% for elect_result in elect_results %}
                   <a href="{% url 'records:elect_details' %}"><h5>Name: {{ elect_result.name_of_students }}</h5></a>
                   <h5>ID: {{ elect_result.id }}</h5>
                    <h5>Amount: {{ elect_result.amount }}</h5>
                    <h5>Balance: {{ elect_result.balance }}</h5>
                {% endfor %}
            {% endif %}
            {% if civil_results %}
                <h4>Results for <b>{{ request.GET.search }} in civil engineering</b></h4>
                {% for civil_result in civil_results %}
                   <a href="{% url 'records:civil_details' %}"><h5>Name: {{ civil_result.name_of_students }}</h5></a>
                   <h5>ID: {{ civil_result.id }}</h5>
                    <h5>Amount: {{ civil_result.amount }}</h5>
                    <h5>Balance: {{ civil_result.balance }}</h5>
                {% endfor %}
            {% endif %}
            {% if comp_sci_results %}
                <h4>Results for <b>{{ request.GET.search }} in computer science department</b></h4>
                {% for comp_sci_result in comp_sci_results %}
                   <a href="{% url 'records:computer_science_details' %}"><h5>Name: {{ comp_sci_result.name_of_students }}</h5></a>
                   <h5>ID: {{ comp_sci_result.id }}</h5>
                    <h5>Amount: {{ comp_sci_result.amount }}</h5>
                    <h5>Balance: {{ comp_sci_result.balance }}</h5>
                {% endfor %}
            {% endif %}
            {% if comp_engr_results %}
                <h4>Results for <b>{{ request.GET.search }} in computer engineering department</b></h4>
                {% for comp_engr_result in comp_engr_results %}
                   <a href="{% url 'records:comp_engr_details' %}"><h5>Name: {{ comp_engr_result.name_of_students }}</h5></a>
                   <h5>ID: {{ comp_engr_result.id }}</h5>
                    <h5>Amount: {{ comp_engr_result.amount }}</h5>
                    <h5>Balance: {{ comp_engr_result.balance }}</h5>
                {% endfor %}
            {% endif %}
            {% if pharm_results %}
                <h4>Results for <b>{{ request.GET.search }} in pharmaceutical technology department</b></h4>
                {% for pharm_result in pharm_results %}
                   <a href="{% url 'records:pharm_tech_details' %}"><h5>Name: {{ pharm_result.name_of_students }}</h5></a>
                   <h5>ID: {{ pharm_result.id }}</h5>
                    <h5>Amount: {{ pharm_result.amount }}</h5>
                    <h5>Balance: {{ pharm_result.balance }}</h5>
                {% endfor %}
            {% endif %}
            {% if sci_results %}
                <h4>Results for <b>{{ request.GET.search }} in science laboratory department</b></h4>
                {% for sci_result in sci_results %}
                    <a href="{% url 'records:science_lab_details' %}"><h5>Name: {{ sci_result.name_of_students }}</h5></a>
                    <h5>ID: {{ sci_result.id }}</h5>
                    <h5>Amount: {{ sci_result.amount }}</h5>
                    <h5>Balance: {{ sci_result.balance }}</h5>
                {% endfor %}
            {% endif %}
            {% if food_results %}
                <h4>Results for <b>{{ request.GET.search }} in Food science department</b></h4>
                {% for food_result in food_results %}
                   <a href="{% url 'records:food_tech_details' %}"><h5>Name: {{ food_result.name_of_students }}</h5></a>
                   <h5>ID: {{ food_result.id }}</h5>
                    <h5>Amount: {{ food_result.amount }}</h5>
                    <h5>Balance: {{ food_result.balance }}</h5>
                {% endfor %}
            {% endif %}
            {% if dispensary_results %}
                <h4>Results for <b>{{ request.GET.search }} in dispensary department</b></h4>
                {% for dispensary_result in dispensary_results %}
                   <a href="{% url 'records:dispense_details' %}"><h5>Name: {{ dispensary_result.name_of_students }}</h5></a>
                   <h5>ID: {{ dispensary_result.id }}</h5>
                    <h5>Amount: {{ dispensary_result.amount }}</h5>
                    <h5>Balance: {{ dispensary_result.balance }}</h5>
                {% endfor %}
            {% endif %}
            {% if agric_results %}
                <h4>Results for <b>{{ request.GET.search }} in agricultural engineering department</b></h4>
                {% for agric_result in agric_results %}
                   <a href="{% url 'records:agric_engr_details' %}"><h5>Name: {{ agric_result.name_of_students }}</h5></a>
                   <h5>ID: {{ agric_result.id }}</h5>
                    <h5>Amount: {{ agric_result.amount }}</h5>
                    <h5>Balance: {{ agric_result.balance }}</h5>
                {% endfor %}
            {% endif %}
            {% else %}
                <h4>No search results for this query</h4>
        {% endif %}
    </div>
</div>
{% endblock content %}