records/urls.py
from django.urls import path
from .import views

app_name = 'records'
urlpatterns = [
    path('', views.home, name='home'),
    path('add_details/', views.add_details, name='add_details'),
    path('mech_details/', views.mech_details, name='mech_details'),
    path('elect_details/', views.elect_details, name='elect_details'),
    path('civil_details/', views.civil_details, name='civil_details'),
    path('comp_engr_details/', views.comp_engr_details, name='comp_engr_details'),
    path('agric_engr_details/', views.agric_engr_details, name='agric_engr_details'),
    path('computer_science_details/', views.computer_science_details, name='computer_science_details'),
    path('science_lab_details/', views.science_lab_details, name='science_lab_details'),
    path('food_tech_details/', views.food_tech_details, name='food_tech_details'),
    path('pharm_tech_details/', views.pharm_tech_details, name='pharm_tech_details'),
    path('dispense_details/', views.dispense_details, name='dispense_details'),
    path('delete_mech/<int:mech_id>/', views.delete_mech, name='delete_mech'),
    path('delete_elect/<int:elect_id>/', views.delete_elect, name='delete_elect'),
    path('delete_civil/<int:civil_id>/', views.delete_civil, name='delete_civil'),
    path('delete_comp_engr/<int:comp_engr_id>/', views.delete_comp_engr, name='delete_comp_engr'),
    path('delete_comp_sci/<int:comp_sci_id>/', views.delete_comp_sci, name='delete_comp_sci'),
    path('delete_agric/<int:agric_id>/', views.delete_agric, name='delete_agric'),
    path('delete_sci_lab/<int:sci_lab_id>/', views.delete_sci_lab, name='delete_sci_lab'),
    path('delete_food/<int:food_id>/', views.delete_food, name='delete_food'),
    path('delete_pharm/<int:pharm_id>/', views.delete_pharm, name='delete_pharm'),
    path('delete_dispense/<int:dispense_id>/', views.delete_dispense, name='delete_dispense'),
    path('mech_update/<int:id>/', views.mech_update, name='mech_update'),
    path('elect_update/<int:id>/', views.elect_update, name='elect_update'),
    path('civil_update/<int:id>/', views.civil_update, name='civil_update'),
    path('comp_sci_update/<int:id>/', views.comp_sci_update, name='comp_sci_update'),
    path('comp_engr_update/<int:id>/', views.comp_engr_update, name='comp_engr_update'),
    path('pharm_update/<int:id>/', views.pharm_update, name='pharm_update'),
    path('sci_lab_update/<int:id>/', views.sci_lab_update, name='sci_lab_update'),
    path('food_update/<int:id>/', views.food_update, name='food_update'),
    path('dispense_update/<int:id>/', views.dispense_update, name='dispense_update'),
    path('agric_update/<int:id>/', views.agric_update, name='agric_update'),
    path('search/', views.search, name='search'),
]

tutorials/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('records.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <title>{% block title %}Union Of FedPoNek Tutors{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/base.css' %}">

  <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
  <meta name="google" content="notranslate" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static "css/style.css" %}">

</head>

<body>


  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'records:home' %}">ACCOUNT DETAILS</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
    
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item text-black">
            <a class="nav-link text-black font-weight-bold" href="{% url 'records:home' %}">Home</a>
          </li>
          <li class="nav-item text-black">
            <a class="nav-link text-black font-weight-bold" href="{% url 'records:mech_details' %}">Mech</a>
          </li>
          <li class="nav-item text-black">
            <a class="nav-link text-black font-weight-bold" href="{% url 'records:elect_details' %}">Elect</a>
          </li>
          <li class="nav-item text-black">
            <a class="nav-link text-black font-weight-bold" href="{% url 'records:civil_details' %}">Civil</a>
          </li>
          <li class="nav-item text-black">
            <a class="nav-link text-black font-weight-bold" href="{% url 'records:comp_engr_details' %}">Comp. Engr.</a>
          </li>
          <li class="nav-item text-black">
            <a class="nav-link text-black font-weight-bold" href="{% url 'records:computer_science_details' %}">Comp. Science</a>
          </li>
          <li class="nav-item text-black">
            <a class="nav-link text-black font-weight-bold" href="{% url 'records:science_lab_details' %}">SLT</a>
          </li>
          <li class="nav-item text-black">
            <a class="nav-link text-black font-weight-bold" href="{% url 'records:food_tech_details' %}">FST</a>
          </li>
          <li class="nav-item text-black">
            <a class="nav-link text-black font-weight-bold" href="{% url 'records:pharm_tech_details' %}">Pharm Tech</a>
          </li>
          <li class="nav-item text-black">
            <a class="nav-link text-black font-weight-bold" href="{% url 'records:dispense_details' %}">DOP</a>
          </li>
          <li class="nav-item text-black">
            <a class="nav-link text-black font-weight-bold" href="{% url 'records:agric_engr_details' %}">Agric. Engr</a>
          </li>
          <li class="nav-item text-black">
            <form action="{% url 'records:search' %}" method="GET" value="{{ request.GET.search }}" class="form-inline">
              <input type="text" id="search" name="search" value="{{ request.GET.search }}" placeholder="Search..">
              <input type="submit" name="submit" id="submit" value="Search"/>
            </form>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}
  <!-- Content Goes here -->
  {% endblock content %}
  </div>

  

   <!-- Footer -->
   <footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center ">Copyright &copy; LUSHAK Communications</p>
  </footer>
  <!-- bootstrap scripts -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>
</body>

</html>